export const ADD_COMMODITY = 'ADD_COMMODITY';
export const REDUCE_COMMODITY = 'REDUCE_COMMODITY';
export const RESET_CART = 'RESET_CART'

export const ADD_SELECT = 'ADD_SELECT';
export const REDUCE_SELECT = 'REDUCE_SELECT';

export const SAVE_USER_INFO = 'SAVE_USER_INFO';

export const SAVE_TYPE_DATA = 'SAVE_TYPE_DATA';

export const CACHE_TYPE = 'CACHE_TYPE';

export const RESET_SELECTED = 'RESET_SELECTED';